#!/usr/bin/env bash

BIN=node_modules/.bin

$BIN/watchify --debug --verbose \
  --require ./index:redux-pouch \
  --extension .es6 \
  --plugin browserify-hmr \
  --transform babelify \
  --outfile example/example.js\
  example/example.es6 &
$BIN/static ./example --port 3000 --cache 0 --host-address 0.0.0.0
